export const THREADS_REPOSITORY = 'THREADS_REPOSITORY'
export const THREADS_NOT_WORK_REPOSITORY = 'THREADS_NOT_WORK_REPOSITORY'
export const THREADS_FAVORITE_REPOSITORY = 'THREADS_FAVORITE_REPOSITORY'